[package]
name = "pathfinder_canvas"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
font-kit = "0.1"

[dependencies.pathfinder_geometry]
path = "../geometry"

[dependencies.pathfinder_renderer]
path = "../renderer"

[dependencies.pathfinder_text]
path = "../text"

[dependencies.skribo]
git = "https://github.com/linebender/skribo.git"
rev = "a89e9ca99e0d6736ea1b7754517f4df14fd96a2b"
