[package]
name = "pathfinder_text"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[dependencies]
euclid = "0.19"
font-kit = "0.1"
lyon_path = "0.12"

[dependencies.pathfinder_geometry]
path = "../geometry"

[dependencies.pathfinder_renderer]
path = "../renderer"

[dependencies.skribo]
git = "https://github.com/linebender/skribo.git"
rev = "f759c2d2c188b668bce998179f03b6319835353e"
